services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"  
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - energywise-network

networks:
  energywise-network:
    driver: bridge