name: CI/CD Pipeline Java Spring

on:
  push:
    branches:
      - main
      - staging

env:
  REGISTRY: docker.io
  IMAGE_NAME: yagolucaas/energywise

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true package

      - name: Run tests
        run: mvn --batch-mode test

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: target/surefire-reports/*.xml
          check_name: "Resultado dos Testes"
          comment_mode: "off"

      - name: Set tag com base no branch
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "TAG=staging" >> $GITHUB_ENV
          fi

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

      - name: Push da imagem para o DockerHub
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$TAG