name: CI/CD Pipeline Java Spring

on:
  push:
    branches:
      - main
      - staging

env:
  REGISTRY: docker.io
  IMAGE_NAME: yagolucaas/energywise

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        run: |
          TAG=$(if [[ "${{ github.ref_name }}" == "main" ]]; then echo "production"; else echo "staging"; fi)
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
          docker push $REGISTRY/$IMAGE_NAME:$TAG

  deploy-to-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref_name == 'main' && 'nome-do-webapp-producao' || 'nome-do-webapp-staging' }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name == 'refs/heads/main' && 'production' || 'staging' }}
